---
title: 'Project 1: Wrangling, Exploration, Visualization'
author: "SDS322E"
date: ''
output:
  html_document:
    toc: yes
    toc_float:
      collapsed: no
      smooth_scroll: yes
  pdf_document:
    toc: no
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = TRUE, fig.align = "center", warning = F, message = F,
tidy=TRUE, tidy.opts=list(width.cutoff=60), R.options=list(max.print=100))
```

## Data Wrangling, Exploration, Visualization

### Nikhil Gumma nrg792

#### Introduction 

Paragraph or two introducing your datasets and variables, why they are interesting to you, etc.

*Netflix has been pushing the boundaries on how our society views content. Their shows have attracted binge-watchers from all over the world to sign up for their monthly subscription. Studies have shown that people are now watching television and online series more frequently than ever. With a Netflix account, one can sit down and start watching a series to escape from reality. However, people are finding that the one episode turns into hours and hours that pass by. This phenomenon of losing track of time while watching series television shows is being termed the “Netflix Effect.” I have always been an avid moviegoer ever since I was a kid. I always loved the experience of being surrounded by random people and escaping reality for two hours. My family used to look forward to movies but, with Netflix on the rise, our weekly plans have shifted to staying at home and watching a new movie on our television. During the pandemic, theaters have seen a steep decline and it seems like the public isn't in any hurry to go back to the theaters. I wanted to see if the content being produced by Netflix is better than the movies being released in the theaters. My goal is to compare Netflix original movies versus the recent theatrical releases based on their IMDb ratings.*

```{R}
data1 <- read.csv("~/project1/IMDbRatings.csv")
data2 <- read.csv("~/project1/NetflixOriginalsRatings.csv")
data1
data2
# read your datasets in here, e.g., with read_csv()
```

#### Tidying: Reshaping

If your datasets are tidy already, demonstrate that you can reshape data with pivot wider/longer here (e.g., untidy and then retidy). Alternatively, it may be easier to wait until the wrangling section so you can reshape your summary statistics. Note here if you are going to do this.

```{R}


library(tidyverse)
mdata2 <- data2 %>% mutate(Name = tolower(Genre))
mdata1 <- data1 %>% select(-modified)
mdata1 <- data1 %>% rename ('Genre'="Genres")
mdata1 <- data1 %>% rename ('Runtime'="Runtime..mins.")
mdata2<- data2
# your tidying code (if applicable; can also wait until wrangling section)

```

    
#### Joining/Merging

```{R}


# your joining code
mdatajoined <- mdata1 %>% full_join(mdata2, by="IMDb.Rating")
moviejoin <- mdatajoined
# of rows in dataset 1 509
mdata1_rows <- nrow(mdata1)
mdata1_rows
# of rows in dataset 2 584
mdata2_rows <- nrow(mdata2)
mdata2_rows
# Number of unique ids in dataset1 509
mdata1_uniqueIds <- mdata1 %>% summarize_all(n_distinct) %>% 
    select(position)
mdata1_uniqueIds
# Number of unique ids in dataset2 584
mdata2_uniqueIds <- mdata2 %>% summarize_all(n_distinct) %>% 
    select(Title)
mdata2_uniqueIds
#Number of movies in first dataset but not other
setdiff(mdata1$Title, mdata2$Title)

setdiff(mdata2$Title, mdata1$Title)
# Number of rows in merged dataset 3238
moviejoined_nrow <- nrow(moviejoin)
moviejoined_nrow
# Number of rows dropped in merged dataset
num_rows_dropped <- nrow(mdata1) + nrow(mdata2) - nrow(moviejoin)


```
*I chose to join the two datasets by IMDb rating since this was a common variable between them both. The IMDb rating is alo the variable I will be using to compare the Netflix films from the other films in the merged dataset. I found 509 rows in the 1st dataset and 584 rows in the second dataset. The number of unique ID's was again 509 for the first data set and 584 for the second one. The Number of unique ID's that appear in the first data that arent in the second one are 506 and vice verse was 581. This is great since we don't want overlap in the films so we can differentiate between Netflix originals and non Netflix movies.*

*The size of the combined dataset is much larger than the inital two data sets since we combined them based on their IMDb score. This is ideal since later on we will be using plots to understand if Netflix movies have a higher IMDb score than others. The number rows that were dropped was 1093 but these rows not have an effect on our dataset since our calculations do not require those values.*
    
Discussions of joining here. Feel encouraged to break up into more than once code chunk and discuss each in turn.

####  Wrangling

```{R}
# your wrangling code
knitr::kable(moviejoin %>% summarize(Mean = mean(Num..Votes, 
    na.rm = TRUE), Standard_Deviation = sd(Num..Votes, na.rm = TRUE), 
    Variance = var(Num..Votes, na.rm = TRUE), `25%_Quantile` = quantile(Num..Votes, 
        0.25, na.rm = TRUE), `50%_Quantile` = quantile(Num..Votes, 
        0.5, na.rm = TRUE), `75%_Quantile` = quantile(Num..Votes, 0.75, 
        na.rm = TRUE), Minimum = min(Num..Votes, na.rm = TRUE), Maximum = max(Num..Votes, 
        na.rm = TRUE), Num_Distinct = n_distinct(Num..Votes, na.rm = TRUE)) %>% 
    na.omit, caption = "Number of Votes used to determine IMDb Score")

# your wrangling code
knitr::kable(moviejoin %>% summarize(Mean = mean(Runtime.y, 
    na.rm = TRUE), Standard_Deviation = sd(Runtime.y, na.rm = TRUE), 
    Variance = var(Runtime.y, na.rm = TRUE), `25%_Quantile` = quantile(Runtime.y, 
        0.25, na.rm = TRUE), `50%_Quantile` = quantile(Runtime.y, 
        0.5, na.rm = TRUE), `75%_Quantile` = quantile(Runtime.y, 0.75, 
        na.rm = TRUE), Minimum = min(Runtime.y, na.rm = TRUE), Maximum = max(Runtime.y, 
        na.rm = TRUE), Num_Distinct = n_distinct(Runtime.y, na.rm = TRUE)) %>% 
    na.omit, caption = "Runtime Statistics of Movies in Joined database")
#IMDb statistics
glimpse(moviejoin)
knitr::kable(moviejoin %>% summarize(Mean = mean(IMDb.Rating, 
    na.rm = TRUE), Standard_Deviation = sd(IMDb.Rating, na.rm = TRUE), 
    Variance = var(IMDb.Rating, na.rm = TRUE), `25%_Quantile` = quantile(IMDb.Rating, 
        0.25, na.rm = TRUE), `50%_Quantile` = quantile(IMDb.Rating, 
        0.5, na.rm = TRUE), `75%_Quantile` = quantile(IMDb.Rating, 0.75, 
        na.rm = TRUE), Minimum = min(IMDb.Rating, na.rm = TRUE), Maximum = max(IMDb.Rating, 
        na.rm = TRUE), Num_Distinct = n_distinct(IMDb.Rating, na.rm = TRUE)) %>% 
    na.omit, caption = "IMDb rating Statistics of Movies in Joined database")
# your wrangling code
knitr::kable(moviejoin %>% group_by(IMDb.Rating) %>% pivot_wider() %>% 
    summarize(Mean = mean(IMDb.Rating, na.rm = TRUE), Standard_Deviation = sd(IMDb.Rating, 
        na.rm = TRUE), Variance = var(IMDb.Rating, na.rm = TRUE), `25%_Quantile` = quantile(IMDb.Rating, 
        0.25, na.rm = TRUE), `50%_Quantile` = quantile(IMDb.Rating, 0.5, 
        na.rm = TRUE), `75%_Quantile` = quantile(IMDb.Rating, 0.75, na.rm = TRUE), 
        Minimum = min(IMDb.Rating, na.rm = TRUE), Maximum = max(IMDb.Rating, na.rm = TRUE), 
        Num_Distinct = n_distinct(IMDb.Rating, na.rm = TRUE)) %>% na.omit %>% 
    arrange(desc(Mean)) %>% slice(1:5) %>% select(IMDb.Rating), caption = "Top 5 IMDb Ratings")
# Top Ratings my Genre
knitr::kable(moviejoin %>% group_by(Genre, Title.x) %>% pivot_wider() %>% 
    summarize(Mean = mean(IMDb.Rating, na.rm = TRUE), Standard_Deviation = sd(IMDb.Rating, 
        na.rm = TRUE), Variance = var(IMDb.Rating, na.rm = TRUE), `25%_Quantile` = quantile(IMDb.Rating, 
        0.25, na.rm = TRUE), `50%_Quantile` = quantile(IMDb.Rating, 0.5, 
        na.rm = TRUE), `75%_Quantile` = quantile(IMDb.Rating, 0.75, na.rm = TRUE), 
        Minimum = min(IMDb.Rating, na.rm = TRUE), Maximum = max(IMDb.Rating, na.rm = TRUE), 
        Num_Distinct = n_distinct(IMDb.Rating, na.rm = TRUE)) %>% na.omit %>% 
    arrange(desc(Mean)) %>% slice(1:2), caption = "Top 2 Highest Rated Movies by Genre")
#Mutate Function
HighlyRated_Metric_Added <- moviejoin%>% mutate( HighlyRated = (IMDb.Rating>7.5))
knitr::kable(HighlyRated_Metric_Added %>% group_by(Genres) %>% summarize(Mean = mean(HighlyRated, 
    na.rm = TRUE), Standard_Deviation = sd(HighlyRated, 
    na.rm = TRUE), Variance = var(HighlyRated, na.rm = TRUE), 
    `25%_Quantile` = quantile(HighlyRated, 0.25, na.rm = TRUE), 
    `50%_Quantile` = quantile(HighlyRated, 0.5, na.rm = TRUE), 
    `75%_Quantile` = quantile(HighlyRated, 0.75, na.rm = TRUE), 
    Minimum = min(HighlyRated, na.rm = TRUE), Maximum = max(HighlyRated, 
        na.rm = TRUE), Num_Distinct = n_distinct(HighlyRated, 
        na.rm = TRUE)) %>% na.omit %>% arrange(desc(Mean)) %>% 
    slice(1:5) %>% select(Genres), caption = "Top 5 Genres based on High IMDb Average Rating")

#Categorical Variable
knitr::kable(moviejoin %>% group_by(Genre) %>% summarize(num_movies = n()))
#Categorical Variable
knitr::kable(moviejoin %>% group_by(Title.type) %>% summarize(num_types = n()))
#Categorical Variable
knitr::kable(moviejoin %>% group_by(Language) %>% summarize(num_Language = n()))

```
*I first used the summary statistics to summarize all the numeric variables that were in my dataset. Some interesting things showed up as a result. The shortest movie in my dataset is only 4 minutes long with the longest being 533 minutes long! Almost 8 Hours! Next I was curious to see the ratings of the movies and it turns out the highest rating is a 9.5! Nobody is perfect I guess. I wanted to explore the Genres of the movies and I found that action, adventure, comedy, fantasy were the most liked Genres! Very interesting to see the decline in Sci-Fci over the years. I personally really enjoy Sci-Fi movies but it looks like they don't score well on IMDb. I introduced my own function to see these results using the mutate function and adding a new variable column called HighlyRated which includes films that have a rating of 7.5 or higher. I then grouped these films by Genre and printed them to see the top genres! For my categorical variables, I summarized them within their column. For the tidydataset I found that my dataset met the cirteria so I didn't have to use anything to modify it. I did use the pivot wider funtion and the knitr::kable to keeps the cleanliness of the knit. *
Your discussion of wrangling section here. Feel encouraged to break up into more than once code chunk and discuss each in turn.


#### Visualizing

```{R}
# your plot 1
library(ggridges)

ggplot(moviejoin, aes(x = IMDb.Rating, color = Num..Votes)) + geom_density(alpha = 0.75) + 
    theme(legend.position = c(0.9, 0.7)) + geom_rug() + scale_x_continuous() + 
    ggtitle("IMDb Rating vs Number of Votes Density Plot") + theme(plot.title = element_text(hjust = 0.5)) + 
    xlab("IMDb Rating") + ylab("Density")
```

Your discussion of plot 1
With this plot, I wanted to see if there was any correlation between the number of votes and the rating of a movie. I was expecting to see a difference on both ends however it looks like the higher ratings have the most votes. This makes sense since a really good movie garners a lot of attentions and so people would really like to express their thoughts after they view it. I was surprised to see the density near the 6.5 range since that is considered a mediocre score. After giving it some thought, I am honesty let down when a movie gets a lot of hype, it's almost like I'm setting myself up to be disappointed.For example, the last Star Wars movie has so much hype but it was really not that great. The higher density in these areas are most likely representative of other audiences feeling the same way. 

```{R}
# your plot 2

library(ggplot2)

ggplot(moviejoin, aes(x = IMDb.Rating, y = Language, color = Title.type )) + 
    geom_point() + geom_smooth(method = "lm") + ggtitle("IMDB Rating vs Runtime Categorized by Language") + 
    theme(plot.title = element_text(hjust = 0.5)) + xlab("IMDb Rating") + 
    ylab("Runtime")

```
Your discussion of plot 2
This plot shows the runtime of each content type based on the language. The x axis shows the IMDb rating for the content type as they are sorted my language. Some interesting points to not are that English movies are shorter in comparison to world cinema. I come from South Asian roots and all the Hindi movies I've seen are very close to three hours. It is interesting to see that some Turkish feature films are much longer than three hours! 

```{R}
# your plot 3
ggplot(moviejoin, aes(x = Title.type, y = IMDb.Rating)) + geom_bar(stat = "summary", 
    fun = mean) + geom_errorbar(stat = "summary", fun.data = mean_se) + 
    scale_y_continuous(breaks = seq()) + ggtitle("Mean IMDb score per Content Type") + 
    theme(plot.title = element_text(hjust = 0.5)) + xlab("Position") + 
    ylab("IMDb Rating")
```
Your discussion of plot 3
This plot shows the Mean IMDb score in terms of Content type for each film. This was the most interesting graph for me to look at since I wanted to see if there was any correlation between if Netflix series were scoring higher than Feature Films. The box plot shows that Mini-Series and TV-Series score higher than Feature Films! I've tried to wrap my brain around the concept of making a tv show versus a film and it does seem like there is more scope to incorporate interesting plot points since there isn't a time constraint. It does give me a new found respect for film makers since it really feels like they are under so much pressure to deliver a good movie with all the ingredients needed without being able to go as deep into the story as a tv series. I can understand why audiences are gravitating towards tv series more these days. There is more substance to immerse yourself in when we talk about tv series.


#### Concluding Remarks

If any!




